### ISSUE TITLE
Vendor Extensions are not available on the Schema object level

### ISSUE THREAD

**Issue by lukastymo** [swagger-api/swagger-spec#312] opened 2015-03-24 15:48 UTC
We use swagger to generate Api and Model. Recently new requirements emerged. It could be solved on the spec level, by providing metadata to our Definitions.

Our spec looks like this:
```
{
  "paths": "...
  "definitions": {
    "Person": {
       "properties": {
           "creditCardNumber": {
              "type": "string"
            }
        }
    }
  }
}
```

Now we would like to add meta data for some of the fields, like this:

```
...
"creditCardNumber": {
   "type": "string",
   "x-group-metadata": "abc"
}
```

Having this extra information we can use it in the generation phase, but it looks like vendor extensions are not possible in this level. 

Swagger-spec 2.0 supports vendor extension only on Info, Paths, Operation, Tag, Security objects.

For now the only possible (quick) workaround is to reuse an existing field:
```
"creditCardNumber": {
   "type": "string",
   "title": "group-metadata=abc"
}
```

**Comment by webron** [comment] 2015-03-24 16:30
Thanks, but this is a duplicate of @241. Feel free to add a comment there for added support.

**Closed by webron** 2015-03-24 16:30 UTC

**Comment by lukastymo** [comment] 2015-03-24 16:43
Wrong title. The #241 is about Schema object, my case is on the Property level

**Comment by webron** [comment] 2015-03-24 16:47
It's still the same suggestion as the properties are part of the JSON Schema which the Schema Object represents. I believe that #241 should be extended to include your suggestion rather than opening a separate issue.

**Comment by lukastymo** [comment] 2015-03-24 16:54
I suppose it's a good idea to link this example with property level to not miss this functionality. 

Looking into code the ModelImpl has been modified so far. I believe that com.wordnik.swagger.models.properties.Property should have such Map too.
