### ISSUE TITLE
Discrepancy found on swagger schema 2.0 and swagger schema description in spec

### ISSUE THREAD

**Issue by pegasusess** [swagger-api/swagger-spec#329] opened 2015-04-16 19:39 UTC
According to swagger schema spec (which can be found on https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md), the field "host" should be as following:

The host (name or ip) serving the API. This MUST be the host only and does not include the scheme nor sub-paths. It MAY include a port. If the  host  is not included, the host serving the documentation is to be used (including the port). The  host  does not support path templating.

According to this definition, ip_address:port_number should make a valid 'host' field. However when I tried to validate my swagger json doc against swagger json schema (which can be found on http://swagger.io/v2/schema.json), 'host' field has to follow the following format:

    "host": {
      "type": "string",
      "format": "uri",
      "pattern": "^[^{}/ :\\\\]+(?::\\d+)?$",
      "description": "The fully qualified URI to the host of the API."
    }

ip_address:port_number failed on this validation check.  Only when I changed it to domain_address:port_number,, this validation check is passed successfully.

this has caused confusion.  Please make the description in spec match with the schema

**Comment by webron** [comment] 2015-04-16 19:51
It's the other way around @pegasusess - the problem is with the schema, not the spec. We caught this issue yesterday and I'm a bit baffled by it. This an issue with the escaping in the regex which shouldn't occur, but I'll investigate more tomorrow.

**Comment by matthewcanty** [comment] 2015-05-06 15:34
This has left me scratching my head for a while. The example `PetStore` swagger file does not validate against the schema.

I'm adding on a port for now - `"host": "api.uber.com:80"`

**Comment by ndhar-1** [comment] 2015-06-18 20:27
+1 
ip_address:port_number fails validation .....

**Comment by hornc** [comment] 2015-07-22 06:17
Hi, I just found this issue after raising a PR that I think fixes this. I ran into a similar confusion around validating using a range of tools, some passed and some failed, here's my PR with my explanation of what I believe is the problem: https://github.com/swagger-api/swagger-spec/pull/420

**Comment by webron** [comment] 2015-07-30 15:05
This is now fixed.

**Closed by webron** 2015-07-30 15:05 UTC
